"""
Django settings for ktvs project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('DEBUG', 'True') == 'True':
        SECRET_KEY = 'django-insecure-default-key'
    else:
        raise ValueError("SECRET_KEY must be set in production!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

# CSRF Protection
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',')
if DEBUG:
    CSRF_COOKIE_SECURE = False

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': ("'self'",),
    'script-src': ("'self'", "'unsafe-inline'", "https://*"),
    'style-src': ("'self'", "'unsafe-inline'", "https://*"),
    'img-src': ("'self'", "data:", "https:"),
    'font-src': ("'self'", "https://*"),
}
X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = 'ktvs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'core.context_processors.active_coupons',
                'core.oauth_logic.oauth_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ktvs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Using SQLite for Django internals (Auth, Admin, Sessions) for High Stability
# Using MongoDB for Business Data (Profiles, Logs, etc.) via PyMongo
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MongoDB Configuration
MONGO_URI = os.getenv('MONGO_URI', 'mongodb://localhost:27017/ktvs')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication Backends
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
)

# Social Auth Settings
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

# Social Auth Configuration
SOCIAL_AUTH_REDIRECT_IS_HTTPS = not DEBUG
SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/dashboard/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/dashboard/'

# Additional OAuth Security Settings
SOCIAL_AUTH_SANITIZE_REDIRECTS = True
SOCIAL_AUTH_PROTECTED_USER_FIELDS = ['email']
SOCIAL_AUTH_SESSION_EXPIRATION = True

# Social Auth Pipeline - Automatically create TOTP profiles for OAuth users
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'core.pipeline.create_totp_profile',  # Custom pipeline to create TOTP profile
)

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Session Security (NIST SP 800-63B)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = True
if DEBUG:   
    SESSION_COOKIE_SECURE = False

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600  # 1 hour timeout
SESSION_SAVE_EVERY_REQUEST = True  # Regenerate session on every request

# Password Hashing - Prefer Argon2, gracefully fall back if unavailable
try:
    import argon2  # noqa: F401

    _ARGON2_AVAILABLE = True
except Exception:  # pragma: no cover - environment specific
    _ARGON2_AVAILABLE = False

if _ARGON2_AVAILABLE:
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.Argon2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    ]
else:
    # Some platforms (e.g. very new Python versions) may not have Argon2 wheels yet.
    # In that case we fall back to PBKDF2 so the project remains runnable.
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    ]

# Encryption Key for sensitive data
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')
if not ENCRYPTION_KEY:
    if DEBUG:
        ENCRYPTION_KEY = 'change-me-in-production-32-chars!!'
    else:
        raise ValueError("ENCRYPTION_KEY must be set in production!")

if len(ENCRYPTION_KEY) < 32:
    raise ValueError('ENCRYPTION_KEY must be at least 32 characters for AES-256')



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
#                               KTVS SETTINGS
# ==============================================================================

KTVS_SETTINGS = {
    'ISSUER': os.getenv('KTVS_ISSUER', 'KTVS'),
    'DEFAULT_KELLEY_ROLE': os.getenv('DEFAULT_KELLEY_ROLE', 'User'),
    'DEFAULT_KELLEY_FUNCTION': os.getenv('DEFAULT_KELLEY_FUNCTION', 'Standard Access'),
    'TOTP_DIGITS': int(os.getenv('TOTP_DIGITS', 6)),
    'TOTP_PERIOD': int(os.getenv('TOTP_PERIOD', 30)),
    'TOTP_ALGORITHM': os.getenv('TOTP_ALGORITHM', 'SHA1'),
    'COUPON_HMAC_SECRET': os.getenv('COUPON_HMAC_SECRET', 'default-secret-change-in-production'),
}

# Feature Flags
ENABLE_OAUTH = os.getenv('ENABLE_OAUTH', 'True') == 'True'
ENABLE_COUPONS = os.getenv('ENABLE_COUPONS', 'True') == 'True'
ENABLE_HIGH_PRIVILEGE = os.getenv('ENABLE_HIGH_PRIVILEGE', 'True') == 'True'
ENABLE_AUDIT_LOGS = os.getenv('ENABLE_AUDIT_LOGS', 'True') == 'True'

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'KTVS QR Code Generator <noreply@ktvs.com>')

